on: push

name: Browser-End-to-end tests-Parallel

jobs:
  Contactus-flow-run:
    name: Contactus flow
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run contactus:run

      - name: Upload Cypress artifacts (Contactus)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: contactus-artifacts-${{ github.run_id }}
          path: |
            cypress/reports
          retention-days: 2

  Subscribe-flow-run:
    name: Subscribe flow
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run subscribe:run

      - name: Upload Cypress artifacts (Subscribe)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: subscribe-artifacts-${{ github.run_id }}
          path: |
            cypress/reports
          retention-days: 2